/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Controlador.*;
import static Main.Expo.tipoU;
import java.awt.Color;
import java.sql.ResultSet;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author Mery Chavez Pacifico
 */
public class Bitacoras extends javax.swing.JInternalFrame {

     Locale locale;
     MtoConsultar consulta = new MtoConsultar();
     MtoLogin log = new MtoLogin();
    /**
     * Creates new form Consultas
     */
    public Bitacoras() {
        initComponents();
        cargarDatos();
        if (Expo.Idioma.equals("English")) {
           locale = new Locale("en","US");
           Internacionalizacion();
        }
        else{
           locale = new Locale("es","ES");
           Internacionalizacion();
 
        } 
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        jTClientes.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        jTClientes.getColumnModel().getColumn(0).setMaxWidth(0);
        
        jTClientes.getTableHeader().getColumnModel().getColumn(2).setMinWidth(0);
        jTClientes.getColumnModel().getColumn(2).setMaxWidth(0);
        if (Expo.darkMode == 1) {
            darkMood();
        }       
    }
    public void darkMood(){
        jPanel4.setBackground(new java.awt.Color(9, 12, 16)); //Fondo
        CustomizeMenu.customizeMenuBar(jMenuBar1);
        jPanel1.setBackground(new java.awt.Color(22, 27, 34)); //Panel de arriba
        jPanel2.setBackground(new java.awt.Color(13, 17, 23)); //Panel principal
        jPanel3.setBackground(new java.awt.Color(22, 27, 34)); //Panel secundario o  lateral
        btnEliminarTodo.setBackground(new java.awt.Color(22, 27, 34));
        btnRefrescar.setBackground(new java.awt.Color(22, 27, 34));
        jTClientes.setGridColor(new java.awt.Color(2,103,255));
//        JTableConsultas.setShowHorizontalLines(true);
//        JTableConsultas.setShowVerticalLines(true);
    } 
    private void Internacionalizacion(){
        ResourceBundle bundle = ResourceBundle.getBundle("Res/Bundle", locale);
        this.setTitle(bundle.getString("Bitacoras.title"));
        jMenu2.setText(bundle.getString("Bitacoras.jMenu2.text"));
        jMenu1.setText(bundle.getString("Bitacoras.jMenu1.text"));
        jMenu3.setText(bundle.getString("Bitacoras.jMenu3.text"));
        jMenuItem1.setText(bundle.getString("Bitacoras.jMenuItem1.text"));
        jMenuItem2.setText(bundle.getString("Bitacoras.jMenuItem2.text"));
        jMenuItem3.setText(bundle.getString("Bitacoras.jMenuItem3.text"));
        jLabel2.setText(bundle.getString("Bitacoras.jLabel2.text"));
        jLabel11.setText(bundle.getString("Bitacoras.jLabel11.text"));
        btnEliminar.setText(bundle.getString("Bitacoras.btnEliminar.text"));
        jLabel12.setText(bundle.getString("Bitacoras.jLabel12.text"));
        btnEliminar1.setText(bundle.getString("Bitacoras.BtnEliminar1.text"));
    }
    
    static ResultSet res;
    private void cargarDatos() {
        String dui = log.getDUI();
        if (tipoU.equals("Cliente")) {
            consulta.ConsultaTabla("SELECT c.idConsulta, c.consulta,cl.nombreCliente,cl.DUI, tc.tipoConsulta FROM dboConsulta c, dboTipoConsulta tc, dboCliente cl where c.idCliente = cl.idCliente and  c.idTipoConsulta = tc.idTipoConsulta AND c.idCliente = (SELECT idCliente FROM dboCliente WHERE DUI = '" + dui + "');", jTClientes);
        } else {
            consulta.ConsultaTabla("SELECT c.idConsulta, c.consulta,cl.nombreCliente,cl.DUI, tc.tipoConsulta FROM dboConsulta c, dboTipoConsulta tc, dboCliente cl where c.idCliente = cl.idCliente and  c.idTipoConsulta = tc.idTipoConsulta;", jTClientes);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTClientes = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        btnRefrescar1 = new rojeru_san.complementos.RSButtonHover();
        btnEliminarTodo = new rojeru_san.complementos.RSButtonHover();
        btnEliminar = new rojeru_san.complementos.RSButtonHover();
        txtId = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnRefrescar = new rojeru_san.complementos.RSButtonHover();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTUsuarios = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        btnEliminarTodo1 = new rojeru_san.complementos.RSButtonHover();
        btnEliminar1 = new rojeru_san.complementos.RSButtonHover();
        txtId2 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Res/Bundle"); // NOI18N
        setTitle(bundle.getString("Bitacoras.title")); // NOI18N

        jPanel4.setBackground(new java.awt.Color(220, 220, 220));
        jPanel4.setAutoscrolls(true);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel2.setText(bundle.getString("Bitacoras.jLabel2.text")); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel1.setText(bundle.getString("Bitacoras.jLabel1.text")); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(730, 40));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1100, 20));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "idConsulta", "Consulta", "Nombre Cliente", "DUI", "Tipo Consulta"
            }
        ));
        jTClientes.getTableHeader().setReorderingAllowed(false);
        jTClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTClientes);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 530, 450));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel11.setText(bundle.getString("Sugerencias.jLabel6.text")); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        btnRefrescar1.setBackground(new java.awt.Color(255, 255, 255));
        btnRefrescar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_refresh_25px_1.png"))); // NOI18N
        btnRefrescar1.setColorHover(new java.awt.Color(240, 240, 240));
        btnRefrescar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescar1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnRefrescar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 40, 40));

        btnEliminarTodo.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminarTodo.setBorder(null);
        btnEliminarTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_delete_database_25px_1.png"))); // NOI18N
        btnEliminarTodo.setColorHover(new java.awt.Color(240, 240, 240));
        btnEliminarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTodoActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminarTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 40, -1));

        btnEliminar.setBackground(new java.awt.Color(51, 51, 51));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_delete_database_25px_1.png"))); // NOI18N
        btnEliminar.setText(bundle.getString("Bitacoras.btnEliminar.text")); // NOI18N
        btnEliminar.setColorHover(new java.awt.Color(255, 102, 102));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 170, 30));
        jPanel2.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 50, -1));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 550, 550));

        jPanel3.setBackground(new java.awt.Color(240, 241, 240));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRefrescar.setBackground(new java.awt.Color(240, 240, 240));
        btnRefrescar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_refresh_25px_1.png"))); // NOI18N
        btnRefrescar.setColorHover(new java.awt.Color(240, 240, 240));
        btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarActionPerformed(evt);
            }
        });
        jPanel3.add(btnRefrescar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 40, 40));

        jTUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "idConsulta", "Consulta", "Nombre Cliente", "DUI", "Tipo Consulta"
            }
        ));
        jTUsuarios.getTableHeader().setReorderingAllowed(false);
        jTUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTUsuariosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTUsuarios);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 530, 450));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel12.setText(bundle.getString("Sugerencias.jLabel6.text")); // NOI18N
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        btnEliminarTodo1.setBackground(new java.awt.Color(240, 240, 240));
        btnEliminarTodo1.setBorder(null);
        btnEliminarTodo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_delete_database_25px_1.png"))); // NOI18N
        btnEliminarTodo1.setColorHover(new java.awt.Color(240, 240, 240));
        btnEliminarTodo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTodo1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnEliminarTodo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 40, -1));

        btnEliminar1.setBackground(new java.awt.Color(51, 51, 51));
        btnEliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_delete_database_25px_1.png"))); // NOI18N
        btnEliminar1.setText(bundle.getString("Bitacoras.btnEliminar1.text")); // NOI18N
        btnEliminar1.setColorHover(new java.awt.Color(255, 102, 102));
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 170, 30));
        jPanel3.add(txtId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 50, -1));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 550, 550));

        jMenu2.setText(bundle.getString("Bitacoras.jMenu2.text")); // NOI18N

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sources/icons8_cancel_20px.png"))); // NOI18N
        jMenuItem1.setText(bundle.getString("Bitacoras.jMenuItem1.text")); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu1.setText(bundle.getString("Bitacoras.jMenu1.text")); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu3.setText(bundle.getString("Bitacoras.jMenu3.text")); // NOI18N

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sources/icons8_whatsapp_20px_1.png"))); // NOI18N
        jMenuItem2.setText(bundle.getString("Bitacoras.jMenuItem2.text")); // NOI18N
        jMenu3.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sources/icons8_computer_support_20px.png"))); // NOI18N
        jMenuItem3.setText(bundle.getString("Bitacoras.jMenuItem3.text")); // NOI18N
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1163, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro que quiere salir del formulario?");
        if (JOptionPane.OK_OPTION == resp) {
            this.dispose();
        }
        else if(JOptionPane.NO_OPTION == resp){

        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed
        cargarDatos();
    }//GEN-LAST:event_btnRefrescarActionPerformed

    private void btnEliminarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTodoActionPerformed
        MtoConsultas obj = new MtoConsultas();
        int eliminar = JOptionPane.showConfirmDialog(this, "Está seguro que desea eliminar todas las consultas?", "Atencion", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(eliminar==0){
            
            if(obj.eliminarTConsulta()){
                JOptionPane.showMessageDialog(this, "Consultas eliminadas");
            }else{
                JOptionPane.showMessageDialog(this, "Error al eliminar");
            }
        }
    
        cargarDatos();
    }//GEN-LAST:event_btnEliminarTodoActionPerformed

    private void jTClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTClientesMouseClicked
        if (jTClientes.getSelectedRowCount()>0) {
            
            txtId.setText(jTClientes.getValueAt(jTClientes.getSelectedRow(), 0).toString());
            btnEliminarTodo.setEnabled(true);
        }
    }//GEN-LAST:event_jTClientesMouseClicked

    private void jTUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTUsuariosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTUsuariosMouseClicked

    private void btnRefrescar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefrescar1ActionPerformed

    private void btnEliminarTodo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTodo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarTodo1ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        MtoConsultas obj = new MtoConsultas();

        if (jTClientes.getSelectedRowCount()>0) {
            obj.setIdConsulta(Integer.parseInt(txtId.getText()));
            int eliminar = JOptionPane.showConfirmDialog(this, "Está seguro que desea eliminar?", "Atencion", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            if(eliminar==0){

                if(obj.eliminarConsulta()){
                    JOptionPane.showMessageDialog(this, "Consulta eliminada");
                }else{
                    JOptionPane.showMessageDialog(this, "Error al eliminar");
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione una consulta primero.");
        }

        cargarDatos();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminar1ActionPerformed
    
   
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.complementos.RSButtonHover btnEliminar;
    private rojeru_san.complementos.RSButtonHover btnEliminar1;
    private rojeru_san.complementos.RSButtonHover btnEliminarTodo;
    private rojeru_san.complementos.RSButtonHover btnEliminarTodo1;
    private rojeru_san.complementos.RSButtonHover btnRefrescar;
    private rojeru_san.complementos.RSButtonHover btnRefrescar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTClientes;
    private javax.swing.JTable jTUsuarios;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtId2;
    // End of variables declaration//GEN-END:variables
}
