package Main;

import java.awt.MouseInfo;
import java.awt.Point;
import javax.swing.*;
import java.util.Locale;
import java.util.ResourceBundle;
/**
 *
 * @author home
 */
public class RecuperarContraseña extends javax.swing.JFrame {

    /**
     * Creates new form RecuperarContraseña
     */
    Locale locale;
    public RecuperarContraseña() {
        initComponents();
        if (Expo.Idioma.equals("English")) {
           locale = new Locale("en","US");
           Internacionalizacion();
        }
        else{
           locale = new Locale("es","ES");
           Internacionalizacion();
 
        }
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/Main/Icon.png")).getImage());
    }
    
    private void Internacionalizacion(){
        ResourceBundle bundle = ResourceBundle.getBundle("Res/Bundle", locale);
        this.setTitle(bundle.getString("RecuperarContraseña.title"));
        jLabel1.setText(bundle.getString("RecuperarContraseña.jLabel1.text"));
        jBtnReturn.setText(bundle.getString("RecuperarContraseña.jBtnReturn.text"));
        jLabel8.setText(bundle.getString("RecuperarContraseña.jLabel8.text"));
        jLabel10.setText(bundle.getString("RecuperarContraseña.jLabel10.text"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBtnReturn = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnMinimizar = new javax.swing.JLabel();
        jBtnQuestion = new rojeru_san.complementos.RSButtonHover();
        jBtnCode = new rojeru_san.complementos.RSButtonHover();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Res/Bundle"); // NOI18N
        setTitle(bundle.getString("RecuperarContraseña.title")); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(63, 94, 102));
        jLabel1.setText(bundle.getString("RecuperarContraseña.jLabel1.text")); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sources/admin.png"))); // NOI18N
        jLabel2.setLabelFor(jLabel2);
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setRequestFocusEnabled(false);
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 230, 230));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sources/question.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 230, 230));

        jBtnReturn.setBackground(new java.awt.Color(204, 204, 255));
        jBtnReturn.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jBtnReturn.setForeground(new java.awt.Color(51, 51, 51));
        jBtnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sources/icons8_expand_arrow_25px_1.png"))); // NOI18N
        jBtnReturn.setText(bundle.getString("RecuperarContraseña.jBtnReturn.text")); // NOI18N
        jBtnReturn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnReturnMouseClicked(evt);
            }
        });
        jPanel2.add(jBtnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 100, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText(bundle.getString("RecuperarContraseña.jLabel8.text")); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, 170, -1));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_red_circle_22px_1.png"))); // NOI18N
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });
        jPanel2.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, -1, 20));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText(bundle.getString("RecuperarContraseña.jLabel10.text")); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, -1, -1));

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_yellow_circle_22px.png"))); // NOI18N
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
        });
        jPanel2.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 5, -1, 20));

        jBtnQuestion.setBackground(new java.awt.Color(255, 255, 255));
        jBtnQuestion.setColorHover(new java.awt.Color(126, 204, 188));
        jBtnQuestion.setColorText(new java.awt.Color(0, 0, 0));
        jBtnQuestion.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jBtnQuestion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBtnQuestion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jBtnQuestion.setIconTextGap(20);
        jBtnQuestion.setMargin(new java.awt.Insets(4, 14, 4, 14));
        jBtnQuestion.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBtnQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnQuestionActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 410, 450));

        jBtnCode.setBackground(new java.awt.Color(255, 255, 255));
        jBtnCode.setColorHover(new java.awt.Color(126, 204, 188));
        jBtnCode.setColorText(new java.awt.Color(0, 0, 0));
        jBtnCode.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jBtnCode.setIconTextGap(20);
        jBtnCode.setMargin(new java.awt.Insets(4, 14, 4, 14));
        jBtnCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCodeActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 410, 450));

        jPanel4.setOpaque(false);
        jPanel4.setRequestFocusEnabled(false);
        jPanel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel4MouseDragged(evt);
            }
        });
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 560));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sources/Login.fw.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 200, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        System.exit(WIDTH);
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    private void jBtnQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnQuestionActionPerformed
        RecuContraQuestion question = new RecuContraQuestion();
        question.show();
        dispose();
    }//GEN-LAST:event_jBtnQuestionActionPerformed

    private void jBtnReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnReturnMouseClicked
        Login login = new Login();
        login.show();
        dispose();
    }//GEN-LAST:event_jBtnReturnMouseClicked

    private void jBtnCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCodeActionPerformed
        RecuContraAdmin code = new RecuContraAdmin();
        code.show();
        dispose();
    }//GEN-LAST:event_jBtnCodeActionPerformed

    int x,y;
    private void jPanel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseDragged
        Point p = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(p.x-x , p.y-y);
    }//GEN-LAST:event_jPanel4MouseDragged

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel4MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecuperarContraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCerrar;
    private javax.swing.JLabel btnMinimizar;
    private rojeru_san.complementos.RSButtonHover jBtnCode;
    private rojeru_san.complementos.RSButtonHover jBtnQuestion;
    private javax.swing.JLabel jBtnReturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
